### ISSUE TITLE
Documentation | Single Source of Truth

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/Tango#293]
At the moment we supported mods / features / the roadmap spread around the repo, website, and discord server. To make life easier for us, and new users to the mod, I'm suggesting that we move all of this information into the GitHub wiki. The website can then directly render these pages as needed.

- [ ]  #152 Roadmap should be moved to https://github.com/CitiesSkylinesMultiplayer/CSM/wiki/Supported-Features
- [ ] Ensure the Discord FAQ and wiki FAQ are synced and matched.
- [ ] A few places in discord mention compatible mods and working features, ensure these are in the wiki
- [ ] Move from GitHub Projects to wiki, a little awkward working with Projects, and it's kind of hidden from everything else

We'll also need to go through the documentation at some point to update it to match current project structure / features
